### PR TITLE
Added network retry lib util function

### PR DESCRIPTION
**Pull request by joelbandi**

### CODE REVIEW

**Review by nlake44 — COMMENTED** [review]
I would not have sleeps since the user is waiting on the response.

**Comment by fedeq** [comment]
@nlake44 I think it's the only way to do it. What do you suggest? Retrying without waiting? Maybe we can retry immediately if it's a 500 error, and wait if its 429

**Comment by nlake44** [comment]
Good call

**Comment by joelbandi** [comment]
This adds a 3 second delay at most and no delay at the 95(aleast) percentile of requests were seeing. Id argue that this should be fine + safer

**Review by fedeq — APPROVED** [review]

**Pull request merged**
